/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AppWorkspaceIndexRouteImport } from './routes/_app/workspace/index'
import { Route as AppWorkspaceMyChannelsRouteImport } from './routes/_app/workspace/my-channels'
import { Route as AppWorkspaceMembersRouteImport } from './routes/_app/workspace/members'
import { Route as AppWorkspaceJourneysRouteImport } from './routes/_app/workspace/journeys'
import { Route as AppWorkspaceConnectorsRouteImport } from './routes/_app/workspace/connectors'
import { Route as AppWorkspaceChannelsRouteImport } from './routes/_app/workspace/channels'
import { Route as AppWorkspaceCadencesRouteImport } from './routes/_app/workspace/cadences'
import { Route as authAcceptInviteTokenRouteImport } from './routes/(auth)/accept-invite.$token'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const AppWorkspaceIndexRoute = AppWorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceMyChannelsRoute = AppWorkspaceMyChannelsRouteImport.update({
  id: '/workspace/my-channels',
  path: '/workspace/my-channels',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceMembersRoute = AppWorkspaceMembersRouteImport.update({
  id: '/workspace/members',
  path: '/workspace/members',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceJourneysRoute = AppWorkspaceJourneysRouteImport.update({
  id: '/workspace/journeys',
  path: '/workspace/journeys',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceConnectorsRoute = AppWorkspaceConnectorsRouteImport.update({
  id: '/workspace/connectors',
  path: '/workspace/connectors',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceChannelsRoute = AppWorkspaceChannelsRouteImport.update({
  id: '/workspace/channels',
  path: '/workspace/channels',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceCadencesRoute = AppWorkspaceCadencesRouteImport.update({
  id: '/workspace/cadences',
  path: '/workspace/cadences',
  getParentRoute: () => AppRouteRoute,
} as any)
const authAcceptInviteTokenRoute = authAcceptInviteTokenRouteImport.update({
  id: '/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/not-found': typeof NotFoundRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/accept-invite/$token': typeof authAcceptInviteTokenRoute
  '/workspace/cadences': typeof AppWorkspaceCadencesRoute
  '/workspace/channels': typeof AppWorkspaceChannelsRoute
  '/workspace/connectors': typeof AppWorkspaceConnectorsRoute
  '/workspace/journeys': typeof AppWorkspaceJourneysRoute
  '/workspace/members': typeof AppWorkspaceMembersRoute
  '/workspace/my-channels': typeof AppWorkspaceMyChannelsRoute
  '/workspace/': typeof AppWorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/not-found': typeof NotFoundRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/accept-invite/$token': typeof authAcceptInviteTokenRoute
  '/workspace/cadences': typeof AppWorkspaceCadencesRoute
  '/workspace/channels': typeof AppWorkspaceChannelsRoute
  '/workspace/connectors': typeof AppWorkspaceConnectorsRoute
  '/workspace/journeys': typeof AppWorkspaceJourneysRoute
  '/workspace/members': typeof AppWorkspaceMembersRoute
  '/workspace/my-channels': typeof AppWorkspaceMyChannelsRoute
  '/workspace': typeof AppWorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/_app': typeof AppRouteRouteWithChildren
  '/not-found': typeof NotFoundRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(auth)/accept-invite/$token': typeof authAcceptInviteTokenRoute
  '/_app/workspace/cadences': typeof AppWorkspaceCadencesRoute
  '/_app/workspace/channels': typeof AppWorkspaceChannelsRoute
  '/_app/workspace/connectors': typeof AppWorkspaceConnectorsRoute
  '/_app/workspace/journeys': typeof AppWorkspaceJourneysRoute
  '/_app/workspace/members': typeof AppWorkspaceMembersRoute
  '/_app/workspace/my-channels': typeof AppWorkspaceMyChannelsRoute
  '/_app/workspace/': typeof AppWorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/not-found'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/accept-invite/$token'
    | '/workspace/cadences'
    | '/workspace/channels'
    | '/workspace/connectors'
    | '/workspace/journeys'
    | '/workspace/members'
    | '/workspace/my-channels'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/not-found'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/accept-invite/$token'
    | '/workspace/cadences'
    | '/workspace/channels'
    | '/workspace/connectors'
    | '/workspace/journeys'
    | '/workspace/members'
    | '/workspace/my-channels'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/_app'
    | '/not-found'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(auth)/verify-email'
    | '/(auth)/accept-invite/$token'
    | '/_app/workspace/cadences'
    | '/_app/workspace/channels'
    | '/_app/workspace/connectors'
    | '/_app/workspace/journeys'
    | '/_app/workspace/members'
    | '/_app/workspace/my-channels'
    | '/_app/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  NotFoundRoute: typeof NotFoundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_app/workspace/': {
      id: '/_app/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof AppWorkspaceIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/workspace/my-channels': {
      id: '/_app/workspace/my-channels'
      path: '/workspace/my-channels'
      fullPath: '/workspace/my-channels'
      preLoaderRoute: typeof AppWorkspaceMyChannelsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/workspace/members': {
      id: '/_app/workspace/members'
      path: '/workspace/members'
      fullPath: '/workspace/members'
      preLoaderRoute: typeof AppWorkspaceMembersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/workspace/journeys': {
      id: '/_app/workspace/journeys'
      path: '/workspace/journeys'
      fullPath: '/workspace/journeys'
      preLoaderRoute: typeof AppWorkspaceJourneysRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/workspace/connectors': {
      id: '/_app/workspace/connectors'
      path: '/workspace/connectors'
      fullPath: '/workspace/connectors'
      preLoaderRoute: typeof AppWorkspaceConnectorsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/workspace/channels': {
      id: '/_app/workspace/channels'
      path: '/workspace/channels'
      fullPath: '/workspace/channels'
      preLoaderRoute: typeof AppWorkspaceChannelsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/workspace/cadences': {
      id: '/_app/workspace/cadences'
      path: '/workspace/cadences'
      fullPath: '/workspace/cadences'
      preLoaderRoute: typeof AppWorkspaceCadencesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(auth)/accept-invite/$token': {
      id: '/(auth)/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof authAcceptInviteTokenRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  authAcceptInviteTokenRoute: typeof authAcceptInviteTokenRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  authAcceptInviteTokenRoute: authAcceptInviteTokenRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppWorkspaceCadencesRoute: typeof AppWorkspaceCadencesRoute
  AppWorkspaceChannelsRoute: typeof AppWorkspaceChannelsRoute
  AppWorkspaceConnectorsRoute: typeof AppWorkspaceConnectorsRoute
  AppWorkspaceJourneysRoute: typeof AppWorkspaceJourneysRoute
  AppWorkspaceMembersRoute: typeof AppWorkspaceMembersRoute
  AppWorkspaceMyChannelsRoute: typeof AppWorkspaceMyChannelsRoute
  AppWorkspaceIndexRoute: typeof AppWorkspaceIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppWorkspaceCadencesRoute: AppWorkspaceCadencesRoute,
  AppWorkspaceChannelsRoute: AppWorkspaceChannelsRoute,
  AppWorkspaceConnectorsRoute: AppWorkspaceConnectorsRoute,
  AppWorkspaceJourneysRoute: AppWorkspaceJourneysRoute,
  AppWorkspaceMembersRoute: AppWorkspaceMembersRoute,
  AppWorkspaceMyChannelsRoute: AppWorkspaceMyChannelsRoute,
  AppWorkspaceIndexRoute: AppWorkspaceIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  NotFoundRoute: NotFoundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
